kind: Pod
apiVersion: v1
metadata:
  name: debug-atlas-server-pv
  namespace: atlas
spec:
  securityContext:
    fsGroup: 1000
  volumes:
    - name: atlas-server-vol
      persistentVolumeClaim:
        claimName: atlas-server-pvc
  containers:
    - name: debugger
      image: busybox
      command: ["sleep", "36000"]
      volumeMounts:
        - mountPath: "/atlas"
          name: atlas-server-vol
