apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: atlas
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: atlas
data:
  redis-config: |
    maxmemory 32gb
    maxmemory-policy allkeys-lru    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: atlas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: atlas-class
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: atlas
  labels:
    app.kubernetes.io/name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
        volumeMounts:
        - mountPath: /redis-master-data
          name: redis-vol
        - mountPath: /redis-master
          name: redis-config
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: redis-config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
