apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: b1
  namespace: atlas
spec:
  selector:
    matchLabels:
      app: b1
  serviceName: "b1-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: b1 
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: b1
        image: antihax/atlas-node
        imagePullPolicy: Always
        command: ["/start-server"]
        args: ["Ocean?ServerX=1?ServerY=0?MaxPlayers=100?ReservedPlayerSlots=5?Port=5004?QueryPort=6004 -AllowedCheatersURL=https://atlas.antihax.net/adminlist -NoBattlEye -server -NoCrashDialog -log -NOCONSOLE"]
        env: 
          - name: WINEDLLOVERRIDES
            value: version=n,b
        ports:
        - containerPort: 5004
          name: game
          protocol: UDP
        - containerPort: 6004
          name: query
          protocol: UDP
        - containerPort: 5005
          name: game2
          protocol: UDP          
        - containerPort: 7004
          name: seamless 
        volumeMounts:
        - name: atlas-server-vol
          mountPath: /atlas
        - name: atlas-configuration-vol
          mountPath: /atlas/ShooterGame/ServerGrid
        - name: save
          mountPath: /atlas/ShooterGame/Saved
        - name: servergrid
          mountPath: /atlas/ShooterGame/ServerGrid.json
          subPath: ServerGrid.json
        - name: servergrid-serveronly
          mountPath: /atlas/ShooterGame/ServerGrid.ServerOnly.json
          subPath: ServerGrid.ServerOnly.json          
      volumes:
      - name: atlas-server-vol
        persistentVolumeClaim:
          claimName: atlas-server-pvc
      - name: atlas-configuration-vol
        persistentVolumeClaim:
          claimName: atlas-configuration-pvc      
      - name: servergrid
        configMap:
          name: servergrid-files
          items:
          - key: "ServerGrid.json"
            path: "ServerGrid.json"                                
      - name: servergrid-serveronly
        configMap:
          name: servergrid-files
          items:
          - key: "ServerGrid.ServerOnly.json"
            path: "ServerGrid.ServerOnly.json"
  volumeClaimTemplates:
  - metadata:
      name: save
      namespace: atlas
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: atlas-class
---
apiVersion: v1
kind: Service
metadata:
  name: b1-headless
  namespace: atlas
  labels:
    app: b1
spec:
  ports:
  - port: 10000
    name: gamex
  selector:
    app: b1
---
apiVersion: v1
kind: Service
metadata:
  name: b1
  namespace: atlas
  labels:
    app: b1
spec:
  type: LoadBalancer
  ports:
  - port: 5004
    name: game
    protocol: UDP
  - port: 6004
    name: query
    protocol: UDP
  - port: 5005
    name: game2
    protocol: UDP    
  - port: 7004
    name: seamless 
    protocol: TCP
  selector:
    app: b1