apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: b2
  namespace: atlas
spec:
  selector:
    matchLabels:
      app: b2
  serviceName: "b2-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: b2 
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: b2
        image: antihax/atlas-node
        imagePullPolicy: Always
        command: ["/start-server"]
        args: ["Ocean?ServerX=1?ServerY=1?MaxPlayers=100?ReservedPlayerSlots=5?Port=5006?QueryPort=6006 -AllowedCheatersURL=https://atlas.antihax.net/adminlist -NoBattlEye -server -NoCrashDialog -log -NOCONSOLE"]
        env: 
          - name: WINEDLLOVERRIDES
            value: version=n,b
        ports:
        - containerPort: 5006
          name: game
          protocol: UDP
        - containerPort: 6006
          name: query
          protocol: UDP
        - containerPort: 5007
          name: game2
          protocol: UDP          
        - containerPort: 7006
          name: seamless 
        volumeMounts:
        - name: atlas-server-vol
          mountPath: /atlas
        - name: atlas-configuration-vol
          mountPath: /atlas/ShooterGame/ServerGrid
        - name: save
          mountPath: /atlas/ShooterGame/Saved
        - name: servergrid
          mountPath: /atlas/ShooterGame/ServerGrid.json
          subPath: ServerGrid.json
        - name: servergrid-serveronly
          mountPath: /atlas/ShooterGame/ServerGrid.ServerOnly.json
          subPath: ServerGrid.ServerOnly.json          
      volumes:
      - name: atlas-server-vol
        persistentVolumeClaim:
          claimName: atlas-server-pvc
      - name: atlas-configuration-vol
        persistentVolumeClaim:
          claimName: atlas-configuration-pvc      
      - name: servergrid
        configMap:
          name: servergrid-files
          items:
          - key: "ServerGrid.json"
            path: "ServerGrid.json"                                
      - name: servergrid-serveronly
        configMap:
          name: servergrid-files
          items:
          - key: "ServerGrid.ServerOnly.json"
            path: "ServerGrid.ServerOnly.json"
  volumeClaimTemplates:
  - metadata:
      name: save
      namespace: atlas
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: atlas-class
---
apiVersion: v1
kind: Service
metadata:
  name: b2-headless
  namespace: atlas
  labels:
    app: b2
spec:
  ports:
  - port: 10000
    name: gamex
  selector:
    app: b2
---
apiVersion: v1
kind: Service
metadata:
  name: b2
  namespace: atlas
  labels:
    app: b2
spec:
  type: LoadBalancer
  ports:
  - port: 5006
    name: game
    protocol: UDP
  - port: 6006
    name: query
    protocol: UDP
  - port: 5007
    name: game2
    protocol: UDP    
  - port: 7006
    name: seamless 
    protocol: TCP
  selector:
    app: b2